ObligatorioP3Parte2/Models/Dominio/Expediente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ObligatorioP3Parte2.Models.Dominio
{
    public class Expediente
    {
        [Key]
        public int id { get; set; }
        public Tramite tramite {get; set;}
        [Display(Name = "Usuario")]
        public string emailLogueado { get; set; }
        public Solicitante solcitante { get; set;}
        public DateTime fechaInicio { get; set; }
        public ICollection<FinalizacionEtapa> etapasFinalizadas { get; set; }
      

    }
}

ObligatorioP3Parte2/Models/Dominio/Solicitante.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace ObligatorioP3Parte2.Models.Dominio
{
    public class Solicitante
    {
        [Key]
        [Required(ErrorMessage = "La cedula es necesaria")]
        [StringLength(10, ErrorMessage = "Supero el limite de caracteres(10)")]
        public string  cedula { get; set; }
        [Required(ErrorMessage = "El nombre es necesaria")]
        [StringLength(15, ErrorMessage = "Supero el limite de caracteres(15)")]
        public string nombre{ get; set; }
        [Required(ErrorMessage = "El apellido es necesaria")]
        [StringLength(15, ErrorMessage = "Supero el limite de caracteres(15)")]
        public string apellido { get; set; }
        [Required(ErrorMessage = "El telefono es necesaria")]
        [StringLength(15, ErrorMessage = "Supero el limite de caracteres(15)")]
        public string  telefono { get; set; }
        [Required(ErrorMessage = "El email es necesaria")]
        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$",
            ErrorMessage = "Formato correo invalido.")]
        public string  email { get; set; }

    }
}

ObligatorioP3Parte2/Models/Dominio/ViewModels/ExpedienteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ObligatorioP3Parte2.Models.Dominio;
using System.Data;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ObligatorioP3Parte2.Models.Dominio.ViewModels
{
  public  class ExpedienteViewModel
    {
      
        public Tramite UnTramite { get; set; }
        public SelectList LosTramites { get; set; }
        public int IdTram { get; set; }
        public Solicitante UnSolicitante { get; set; }
        public DateTime fecha { get; set; }

        public ExpedienteViewModel()
        {

            this.UnTramite = new Tramite();
            this.IdTram = UnTramite.idTramite;
            cargarTramites();
            fecha = DateTime.Now;
        }
  

        private void cargarTramites()
        {
            OficinaContext db = new OficinaContext();
            this.LosTramites = new SelectList(db.Tramite.ToList(), "IdTramite", "Titulo");
        }

    }
}

ObligatorioP3Parte2/Controllers/ExpedientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ObligatorioP3Parte2.Models.Dominio;
using ObligatorioP3Parte2.Models.Dominio.ViewModels;

namespace ObligatorioP3Parte2.Controllers
{
    public class ExpedientesController : Controller
    {
        private OficinaContext db = new OficinaContext();

        // GET: Expedientes
        public ActionResult Index()
        {
            return View(db.Expediente.ToList());
        }
        public ActionResult FiltroPorId(string id)
        {

            var expedientes = db.Expediente.Include(f => f.solcitante);
                                
            int idparseado = 0;
            int.TryParse(id, out idparseado);
            if (!String.IsNullOrEmpty(id))
            {
                expedientes = expedientes.Where(s => s.id==idparseado);
                return View(expedientes.ToList());
            }
            expedientes = db.Expediente.Include(f => f.solcitante).OrderByDescending(f =>f.solcitante.cedula).ThenByDescending(f=> f.fechaInicio);
    
            return View(expedientes.ToList());
        }

        public ActionResult FiltroPorCedula(string cedula)
        {
            var expedientes = db.Expediente.Include(f => f.solcitante);


            if (!String.IsNullOrEmpty(cedula))
            {
                expedientes = expedientes.Where(s => s.solcitante.cedula==cedula);
                return View("FiltroPorId",expedientes.ToList());
            }
            expedientes = db.Expediente.Include(f => f.solcitante).OrderByDescending(f => f.solcitante.cedula).ThenByDescending(f => f.fechaInicio);
            return View("FiltroPorId",expedientes.ToList());

        }

        public ActionResult FiltroPorFuncionario(string funcionario)
        {
            var expedientes = db.Expediente.Include(f => f.solcitante);        
            //expedientes =
            //             from exp in db.Expediente.Include("Solcitante")
            //             join EtapaFinal in db.FinalizacionEtapa on exp.id equals EtapaFinal.Expediente.id
            //             join func in db.Funcionario on EtapaFinal.funcionario.email equals func.email
            //             where EtapaFinal.funcionario.email == funcionario
            //             select exp;
            //expedientes = expedientes.Distinct();
          
            if (!String.IsNullOrEmpty(funcionario))
            {
                expedientes =
             from EtapaFinal in db.FinalizacionEtapa
             join func in db.Funcionario on EtapaFinal.funcionario.email equals func.email
             join exp in db.Expediente on EtapaFinal.Expediente.id equals exp.id
             where EtapaFinal.funcionario.email == funcionario
             select exp;
                expedientes = expedientes.Distinct();

                return View("FiltroPorId", expedientes.ToList());
            }
            expedientes = db.Expediente.Include(f => f.solcitante).OrderByDescending(f => f.solcitante.cedula).ThenByDescending(f => f.fechaInicio);
            return View("FiltroPorId", expedientes.ToList());

        }

        //public ActionResult FiltroPorExpedienteCulminado()
        //{
        //    var expedientes = db.Expediente.Include(f => f.solcitante);

        //    expedientes =
        //                  from EtapaFinal in db.FinalizacionEtapa 
        //                  join exp in db.Expediente.Include("Solcitante") on EtapaFinal.Expediente.id equals exp.id
        //                  select exp;
        //        expedientes = expedientes.Distinct();
            

        //    return View("FiltroPorId", expedientes.ToList());

        //}
        public ActionResult FiltroPorExpedienteCulminado()
        {
           
            var expedientes = db.Expediente.Include(f => f.solcitante);

            expedientes =
                          from exp in db.Expediente.Include("Tramite")
                          
                          select exp;
            expedientes = expedientes.Distinct();
            expedientes.ToList();
            List<Expediente> ExpCulminados = new List<Expediente>();
            foreach (Expediente ex in expedientes)
            {
                using (OficinaContext db = new OficinaContext())
                {

                    var tramite = from et in db.Tramite.Include("Etapas")
                                  where et.idTramite == ex.tramite.idTramite
                                  select et;
                    tramite = tramite.Distinct();
                    Tramite tram = tramite.FirstOrDefault();
                    List < Etapa > etapas = new List<Etapa>();
                    foreach (Etapa et in tram.etapas)
                    {
                        etapas.Add(et);
                    }
                    var fes = from fe in db.FinalizacionEtapa
                             where ex.id == fe.Expediente.id
                             select fe;
                    fes = fes.Distinct();
                    fes.ToList();


                    if (fes.Count() == etapas.Count())
                    {
                        ExpCulminados.Add(ex);
                    }
                } 
                
            }

            return View("FiltroPorId", ExpCulminados);

        }

        //public ActionResult FiltroPorExpedienteNoCulminado()
        //{
        //    var expedientes = db.Expediente.Include(f => f.solcitante);
        //    expedientes =
        //                from expediente in db.Expediente.Include("Solcitante")
        //                where !(from Etapa in db.FinalizacionEtapa
        //                        select Etapa.Expediente.id)
        //                        .Contains(expediente.id)
        //                select expediente;
        //    expedientes = expedientes.Distinct();


        //    return View("FiltroPorId", expedientes.ToList());

        //}

        public ActionResult FiltroPorExpedienteNoCulminado()
        {
            var expedientes = db.Expediente.Include(f => f.solcitante);

            expedientes =
                          from exp in db.Expediente.Include("Tramite")

                          select exp;
            expedientes = expedientes.Distinct();
            expedientes.ToList();
            List<Expediente> ExpCulminados = new List<Expediente>();
            foreach (Expediente ex in expedientes)
            {
                using (OficinaContext db = new OficinaContext())
                {

                    var tramite = from et in db.Tramite.Include("Etapas")
                                  where et.idTramite == ex.tramite.idTramite
                                  select et;
                    tramite = tramite.Distinct();
                    Tramite tram = tramite.FirstOrDefault();
                    List<Etapa> etapas = new List<Etapa>();
                    foreach (Etapa et in tram.etapas)
                    {
                        etapas.Add(et);
                    }
                    var fes = from fe in db.FinalizacionEtapa
                              where ex.id == fe.Expediente.id
                              select fe;
                    fes = fes.Distinct();
                    fes.ToList();


                    if (fes.Count() != etapas.Count())
                    {
                        ExpCulminados.Add(ex);
                    }
                }

            }

            return View("FiltroPorId", ExpCulminados);

        }



        // GET: Expedientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expediente expediente = db.Expediente.Find(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }
            return View(expediente);
        }
        public ActionResult Solicitante()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Solicitante(string cedula)
        {
            try
            {
                using (OficinaContext db = new OficinaContext())
                {
                    var sol = db.Solicitante.SingleOrDefault
                        (u => u.cedula.ToUpper() == cedula.ToUpper());

                    Solicitante solicitante = sol;  
                    if (sol == null)
                    {
                        return RedirectToAction("CreateSolicitante");

                    }
                    TempData["Solicitante"] = solicitante;
                    return RedirectToAction("ListaTramites");
                }
            }
            catch
            {
                return View();
            }
        }
        public ActionResult CreateSolicitante()
        {
            return View();
        }


        // POST: Expedientes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSolicitante([Bind(Include = "cedula,nombre,apellido,telefono,email")] Solicitante solicitante)
        {
            if (ModelState.IsValid)
            {
                using (OficinaContext db = new OficinaContext())
                {
                    var sol = db.Solicitante.SingleOrDefault
                        (u => u.cedula.ToUpper() == solicitante.cedula.ToUpper());

ObligatorioP3Parte2/Views/Expedientes/Create.cshtml
@model ObligatorioP3Parte2.Models.Dominio.Expediente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expediente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.emailLogueado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailLogueado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailLogueado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ObligatorioP3Parte2/Views/Expedientes/CreateSolicitante.cshtml
@model ObligatorioP3Parte2.Models.Dominio.Solicitante
@if (Session["Usuario"] == null)
{ @Html.Action("Index", "Home") }
@{
    ViewBag.Title = "CreateSolicitante";
}

<h2>CreateSolicitante</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Solicitante</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ObligatorioP3Parte2/Views/Expedientes/Delete.cshtml
@model ObligatorioP3Parte2.Models.Dominio.Expediente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expediente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.emailLogueado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailLogueado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ObligatorioP3Parte2/Views/Expedientes/Details.cshtml
@model ObligatorioP3Parte2.Models.Dominio.Expediente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Expediente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.emailLogueado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailLogueado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicio)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ObligatorioP3Parte2/Views/Expedientes/Edit.cshtml
@model ObligatorioP3Parte2.Models.Dominio.Expediente

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expediente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.emailLogueado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailLogueado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailLogueado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ObligatorioP3Parte2/Views/Expedientes/FiltroPorId.cshtml
@model IEnumerable<ObligatorioP3Parte2.Models.Dominio.Expediente>
@if (Session["Usuario"] == null)
{ @Html.Action("Index", "Home") }
@{
    ViewBag.Title = "FiltroPorId";
}

<h2>Listado de expedientes</h2>


@using (Html.BeginForm("FiltroPorId", "Expedientes"))
{
    <p>
        Busqueda por id expdiente: @Html.TextBox("id")<br />
        <input type="submit" value="Filtrar" />
    </p>
}

@using (Html.BeginForm("FiltroPorCedula", "Expedientes"))
{
    <p>
        Busqueda por cedula del solicitante: @Html.TextBox("cedula")<br />
        <input type="submit" value="Filtrar" />
    </p>
}

@using (Html.BeginForm("FiltroPorFuncionario", "Expedientes"))
{
    <p>
        Expedientes de un funcionario: @Html.TextBox("funcionario")<br />
        <input type="submit" value="Filtrar" />
    </p>
}
@using (Html.BeginForm("FiltroPorExpedienteCulminado", "Expedientes"))
{
    <p>
        Expedientes culminados
        <input type="submit" value="Filtrar" />
    </p>
}
@using (Html.BeginForm("FiltroPorExpedienteNoCulminado", "Expedientes"))
{
    <p>
        Expedientes NO culminados
        <input type="submit" value="Filtrar" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.emailLogueado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.solcitante.cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaInicio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.emailLogueado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.solcitante.cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaInicio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

ObligatorioP3Parte2/Views/Expedientes/Index.cshtml
@model IEnumerable<ObligatorioP3Parte2.Models.Dominio.Expediente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.emailLogueado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaInicio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.emailLogueado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaInicio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

ObligatorioP3Parte2/Views/Expedientes/ListaTramites.cshtml
@model ObligatorioP3Parte2.Models.Dominio.ViewModels.ExpedienteViewModel
@if (Session["Usuario"] == null)
{ @Html.Action("Index", "Home") }
@{
    ViewBag.Title = "ListaTramites";
}

<h2>Lista de Tramites</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Seleccione el tramite que desea guardar en el expediente</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdTram, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdTram, Model.LosTramites)
                @Html.HiddenFor(model => model.IdTram, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTram, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



ObligatorioP3Parte2/Views/Expedientes/Solicitante.cshtml
@model ObligatorioP3Parte2.Models.Dominio.Solicitante

@if (Session["Usuario"] == null)
{ @Html.Action("Index", "Home") }

@{
    ViewBag.Title = "Solicitante";
}


<h2>Solicitante</h2>

@using (Html.BeginForm("Solicitante", "Expedientes", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Solicitante</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
            </div>
        </div>      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

    


